### ISSUE TITLE
macOS builds and releases

### ISSUE THREAD

**Issue by iBobik** [AudMonkey/AudMonkey#32]
Build macOS app and release it in releases.

Nice to have: Add to Brew repository.

**Comment by IshoAntar** [comment]
A MacOS build is available in the [latest release](https://github.com/AudMonkey/AudMonkey/releases/tag/v1.0.1) (and will be for subsequent releases!).

But i'm not sure if it works or not (no reason why it shouldn't. i'm just being pedantic :) )
and i don't have access to a Mac, if you do, could you test it to see if it works?

**Comment by iBobik** [comment]
Seems working, thanks :-)
